# Generated by Django 5.0.3 on 2024-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingests', '0004_column_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='process_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingest',
            name='processed_row_nums',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingest',
            name='row_nums',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
