# Generated by Django 5.0.3 on 2024-03-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingests', '0006_alter_ingest_process_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='file_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
